// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('addReviewOfBusiness', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('addReviewOfBusiness', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(1246, 812)
    await driver.findElement(By.css(".remove-link-style:nth-child(2) .bus-logo")).click()
    await driver.findElement(By.css(".comment-box")).click()
    await driver.findElement(By.css(".comment-box")).sendKeys("New comment")
    await driver.findElement(By.css(".btn")).click()
  })
})
