// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('createNewBusiness', function() {
    this.timeout(30000)
    let driver
    let vars
    beforeEach(async function() {
        driver = await new Builder().forBrowser('chrome').build()
        vars = {}
    })
    afterEach(async function() {
        await driver.quit();
    })
    it('createNewBusiness', async function() {
        await driver.get("http://localhost:3000/")
        await driver.manage().window().setRect(1246, 812)
        await driver.findElement(By.linkText("Register a Business")).click()
        await driver.findElement(By.id("businessname")).click()
        await driver.findElement(By.id("businessname")).sendKeys("NewBusiness")
        await driver.findElement(By.id("email")).sendKeys("newBusiness@nb.com")
        await driver.findElement(By.id("sel1")).click()
        {
            const dropdown = await driver.findElement(By.id("sel1"))
            await dropdown.findElement(By.xpath("//option[. = 'Entertainment']")).click()
        }
        await driver.findElement(By.id("sel1")).click()
        await driver.findElement(By.id("comment")).click()
        await driver.findElement(By.css(".form-group:nth-child(5) > #comment")).click()
        await driver.findElement(By.css(".form-group:nth-child(5) > #comment")).sendKeys("New entertaining business")
        await driver.findElement(By.id("address")).sendKeys("Address 1")
        await driver.findElement(By.css(".form-group:nth-child(3) > #sel1")).click()
        {
            const dropdown = await driver.findElement(By.css(".form-group:nth-child(3) > #sel1"))
            await dropdown.findElement(By.xpath("//option[. = 'Uganda']")).click()
        }
        await driver.findElement(By.css(".form-group:nth-child(3) > #sel1")).click()
        await driver.findElement(By.css("fieldset:nth-child(3) > .form-group:nth-child(4) > #sel1")).click()
        {
            const dropdown = await driver.findElement(By.css("fieldset:nth-child(3) > .form-group:nth-child(4) > #sel1"))
            await dropdown.findElement(By.xpath("//option[. = 'Lagos']")).click()
        }
        await driver.findElement(By.css("fieldset:nth-child(3) > .form-group:nth-child(4) > #sel1")).click()
        await driver.findElement(By.css(".form-group:nth-child(5) > #sel1")).click()
        {
            const dropdown = await driver.findElement(By.css(".form-group:nth-child(5) > #sel1"))
            await dropdown.findElement(By.xpath("//option[. = 'Ikeja']")).click()
        }
        await driver.findElement(By.css(".form-group:nth-child(5) > #sel1")).click()
        await driver.findElement(By.name("zipcode")).sendKeys("111222")
        await driver.findElement(By.id("telephone")).sendKeys("1")
        await driver.findElement(By.id("telephone")).click()
        await driver.findElement(By.id("telephone")).sendKeys("2")
        await driver.findElement(By.id("telephone")).click()
        await driver.findElement(By.id("telephone")).sendKeys("3")
        await driver.findElement(By.id("telephone")).click()
        await driver.findElement(By.id("telephone")).sendKeys("4")
        await driver.findElement(By.id("telephone")).click()
        {
            const element = await driver.findElement(By.id("telephone"))
            await driver.actions({ bridge: true}).doubleClick(element).perform()
        }
        await driver.findElement(By.id("telephone")).sendKeys("5")
        await driver.findElement(By.id("telephone")).click()
        await driver.findElement(By.id("telephone")).sendKeys("4")
        await driver.findElement(By.id("telephone")).click()
        await driver.findElement(By.id("telephone")).sendKeys("3")
        await driver.findElement(By.id("telephone")).click()
        {
            const element = await driver.findElement(By.id("telephone"))
            await driver.actions({ bridge: true}).doubleClick(element).perform()
        }
        await driver.findElement(By.id("telephone")).sendKeys("2")
        await driver.findElement(By.id("telephone")).click()
        await driver.findElement(By.id("telephone")).sendKeys("1")
        await driver.findElement(By.id("telephone")).click()
        await driver.findElement(By.id("telephone")).sendKeys("0")
        await driver.findElement(By.id("telephone")).click()
        await driver.findElement(By.id("telephone")).sendKeys("-1")
        await driver.findElement(By.id("telephone")).click()
        // {
        //     const element = await driver.findElement(By.css(".container"))
        //     await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
        // }
        // {
        //     const element = await driver.findElement(By.css(".container"))
        //     await driver.actions({ bridge: true }).moveToElement(element).perform()
        // }
        // {
        //     const element = await driver.findElement(By.css(".container"))
        //     await driver.actions({ bridge: true }).moveToElement(element).release().perform()
        // }
        await driver.findElement(By.css(".container")).click()
        await driver.findElement(By.id("telephone")).sendKeys("77774441155")
        await driver.findElement(By.css("fieldset:nth-child(4) > legend")).click()
        await driver.findElement(By.css(".btn")).click()
    })
})
