// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('searchForBusiness_find', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('searchForBusiness_find', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(1246, 812)
    await driver.findElement(By.css(".search-input")).click()
    await driver.findElement(By.css(".search-input")).sendKeys("abc")
    await driver.findElement(By.css(".btn-submit")).click()
  })
})
