// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('searchForBusiness_location', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('searchForBusiness_location', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(1246, 812)
    await driver.findElement(By.xpath("(//select[@id=\'sel1\'])[2]")).click()
    {
      const dropdown = await driver.findElement(By.xpath("(//select[@id=\'sel1\'])[2]"))
      await dropdown.findElement(By.xpath("//option[. = 'Uganda']")).click()
    }
    await driver.findElement(By.xpath("(//select[@id=\'sel1\'])[2]")).click()
    await driver.findElement(By.css(".btn-submit")).click()
  })
})
