// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('http://localhost:3000/', function() {
    this.timeout(300000)
    let driver
    let vars
    beforeEach(async function() {
        driver = await new Builder().forBrowser('chrome').build()
        vars = {}
    })
    afterEach(async function() {
        await driver.quit();
    })
    async function waitForWindow(timeout = 50000) {
        await driver.sleep(timeout)

        await driver.getAllWindowHandles().then(async (allhandles) => { return await driver.switchTo().window(allhandles[allhandles.length - 1]); });

        // const handlesThen = vars["windowHandles"]
        // const handlesNow = await driver.getAllWindowHandles()
        // if (handlesNow.length > handlesThen.length) {
        //     return handlesNow.find(handle => (!handlesThen.includes(handle)))
        // }
        // throw new Error("New window did not appear before timeout")
    }
    it('http://localhost:3000/', async function() {
        vars["windowHandles"] = await driver.getAllWindowHandles()
        await driver.get("http://localhost:3000/")
        vars["w"] = await waitForWindow(100)
        await driver.manage().window().setRect(1246, 812)
        await driver.findElement(By.id("sel1")).click()
        {
            const dropdown = await driver.findElement(By.id("sel1"))
            await dropdown.findElement(By.xpath("//option[. = 'Technology']")).click()
        }
        await driver.findElement(By.id("sel1")).click()
        await driver.findElement(By.css(".btn-submit")).click()
        await driver.findElement(By.css(".remove-link-style:nth-child(1) > .business-card .business-name")).click()
    })
})
