// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('signUp', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('signUp', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(1246, 812)
    await driver.findElement(By.linkText("Sign Up")).click()
    await driver.findElement(By.id("firstname")).click()
    await driver.findElement(By.id("firstname")).sendKeys("New")
    await driver.findElement(By.id("lastname")).sendKeys("User")
    await driver.findElement(By.id("email")).sendKeys("newUser@nb.com")
    await driver.findElement(By.id("pwd")).sendKeys("pass")
    await driver.findElement(By.name("repswd")).sendKeys("pass")
    await driver.findElement(By.css(".btn")).click()
  })
})
